/**
 * Preloaded curated list of Universities and Colleges in Delhi-NCR, Haryana, and North India.
 */
export const PRELOADED_COLLEGES: string[] = [
  "Lingaya's Vidyapeeth, Faridabad",
  "Manav Rachna International Institute of Research and Studies (MRIIRS), Faridabad",
  "J.C. Bose University of Science and Technology, YMCA, Faridabad",
  "Amity University, Noida",
  "Sharda University, Greater Noida",
  "Galgotias University, Greater Noida",
  "Bennett University, Greater Noida",
  "Shiv Nadar University, Greater Noida",
  "Delhi Technological University (DTU), Delhi",
  "Netaji Subhas University of Technology (NSUT), Delhi",
  "Indira Gandhi Delhi Technical University for Women (IGDTUW), Delhi",
  "Guru Gobind Singh Indraprastha University (GGSIPU), Delhi",
  "Maharaja Agrasen Institute of Technology (MAIT), Delhi",
  "Bhagwan Parshuram Institute of Technology (BPIT), Delhi",
  "Bharati Vidyapeeth's College of Engineering (BVCOE), Delhi",
  "Maharaja Surajmal Institute of Technology (MSIT), Delhi",
  "Jamia Millia Islamia, Delhi",
  "University of Delhi (DU) - Hansraj College",
  "University of Delhi (DU) - Hindu College",
  "University of Delhi (DU) - Kirori Mal College",
  "University of Delhi (DU) - Sri Venkateswara College",
  "University of Delhi (DU) - Ramjas College",
  "University of Delhi (DU) - St. Stephen's College",
  "University of Delhi (DU) - Gargi College",
  "University of Delhi (DU) - Miranda House",
  "K.R. Mangalam University, Gurugram",
  "GD Goenka University, Gurugram",
  "The NorthCap University (NCU), Gurugram",
  "SGT University, Gurugram",
  "BML Munjal University, Gurugram",
  "SRM University, Delhi-NCR, Sonepat",
  "O.P. Jindal Global University, Sonepat",
  "Ashoka University, Sonepat",
  "Deenbandhu Chhotu Ram University of Science and Technology (DCRUST), Murthal",
  "Maharshi Dayanand University (MDU), Rohtak",
  "Kurukshetra University, Kurukshetra",
  "National Institute of Technology (NIT), Kurukshetra",
  "Indian Institute of Technology (IIT), Delhi",
  "IIT Delhi - Sonipat Campus",
  "Chanderprabhu Jain College of Higher Studies, Narela",
  "Rawal Institutions, Faridabad",
  "Echelon Institute of Technology, Faridabad",
  "B.S. Anangpuria Institute of Technology and Management, Faridabad",
  "Aravali College of Engineering and Management, Faridabad",
];
